### ISSUE TITLE
发布到 gitbook 上去？

### ISSUE THREAD

**Issue by zhuangya** [lexdene/gcc_five_minute#12]
我觉得可以发布到 gitbook 上去呀

理论上来说你把这个 repo 导入给 gitbook 就应该差不多好了

顺路：

大象阿，之前没发现原来你还写过这样的东西

点赞

**Comment by lexdene** [comment]
gitbook build error

> No SUMMARY file

似乎要加几个配置文件的。
懒得弄了。

PS:

这是我之前学 C++ 的时候写的，好久不更新了。

**Comment by lexdene** [comment]
已发布到 gitbook 。

我发现 SUMMARY file 的格式很简单，写了个 shell 脚本自动生成了一下。然后发布就成功了。
